branch-defaults:
  default:
    environment: null
global:
  application_name: myenv-1
  default_ec2_keyname: null
  default_platform: Python 3.4
  default_region: ap-southeast-2
  profile: myprofile1
  sc: null
